databases:
  - name: shared-calendar-db
    plan: free
    databaseName: sharedcalendar
    user: sharedcalendar

services:
  - type: web
    name: shared-calendar-be
    runtime: docker
    repo: https://github.com/easywaldo/shared-calendar-be.git
    branch: main
    plan: free
    healthCheckPath: /api/members/health
    envVars:
      - key: PORT
        value: 8080
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DATABASE_URL
        fromDatabase:
          name: shared-calendar-db
          property: connectionString
