services:
  - type: web
    name: shared-calendar-be
    runtime: docker
    repo: https://github.com/easywaldo/shared-calendar-be.git
    branch: main
    plan: free
    healthCheckPath: /api/members
    envVars:
      - key: PORT
        value: 8080
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: TURSO_DATABASE_URL
        value: https://test-app-db-vercel-icfg-tmg7blpxjgjzolqatm2nubnm.aws-ap-northeast-1.turso.io
      - key: TURSO_AUTH_TOKEN
        value: REDACTED_TURSO_TOKEN
